//labels and text for categories and metrics - baking this into the html for now
/*
var catname = {
    main: "Population",
    origin: "Country of origin",
    citizenship: "Citizenship",
    edukids: "Education of children",
    edupar: "Education of parents",
    engkids: "English proficiency of children",
    engpar: "English proficiency of parents",
    numkids: "Number of children in household",
    numpar: "Number of parents in household",
    incbenefits: "Income and benefits"
};
*/

//text for levels of categories - make all edits here
var levels = {
    main: ["All children", "Birth to age 3", "Ages 4 to 5", "Ages 6 to 12", "Ages 13 to 17"],
    //age: ["Age 0 to 3", "Age 4 to 5", "Age 6 to 12", "Age 13 to 17"],
    origin: ["Mexico", "Rest of Central America or the Spanish Caribbean", "Europe, Canada, Australia, or New Zealand", "East Asia or the Pacific", "Africa or the West Indies", "Middle East or South Asia", "South America", "Southeast Asia"],
    citizenship: ["US citizen with at least one US-citizen parent", "US citizen with only noncitizen parents", "Noncitizen"],
    edukids: ["In preschool, ages 3 to 5", "In kindergarten or grade school, ages 3 to 5", "Not in school, ages 3 to 5", "Not in school, ages 6 to 17"],
    edupar: ["All parents have less than a high school education", "At least one parent has a high school education, some college, or an associate’s degree; none has a four-year college degree or more", "At least one parent has a four-year college degree or more"],
    engkids: ["English proficient", "Limited English proficiency"],
    engpar: ["All English-proficient parents", "At least one parent has limited English proficiency", "All parents have limited English proficiency", "Linguistically isolated households"],
    numkids: ["1", "2", "3–4", "5+"],
    numpar: ["One parent", "Two parents"],
    incbenefits: ["Family with income below poverty level", "Family with low income", "Family with substantial work hours", "Family with low income and substantial work hours", "Not covered by health insurance"],
    housetrans: ["Household owns home", "Severely burdened by housing and utility costs", "Somewhat burdened by housing and utility costs", "Not burdened by housing and utility costs", "Multiple household vehicles available", "One household vehicle available", "No household vehicles available"],
    paryears: ["One or more foreign-born parents in US fewer than 5 years", "One or more foreign-born parents in US 5–9 years, none fewer than 5", "One or more foreign-born parents in US 10–19 years, none fewer than 10", "All foreign-born parents in US 20 years or more"],
    disabledfam: ["At least one parent has a disability", "At least one adult in family has a disability, but no parent has a disability", "No adults in family have a disability"],
    vetpar: ["Has veteran parent(s)", "No veteran parents"],
    race: ["Hispanic", "Asian or Pacific Islander", "White", "Black", "Another race or multiracial"]
};

//summary text for each category
var cattext = {
    main: "<p>The number of children of immigrants (i.e., children with at least one immigrant parent) increased from 16.0 million in 2006 to more than 18 million in recent years, and the share of all children that are children of immigrants increased slightly from 22 to about 25 percent during the same period. A majority—59 percent—of these children live in six states that are traditional immigrant destinations: California, New York, New Jersey, Florida, Illinois, and Texas. But many of these traditional immigrant destinations have not seen significant growth in the past several years, while the share of children of immigrants in some nontraditional states, such as Maryland and Washington, has grown.</p>",
    //age: "Share of children in a certain age group that are children of immigrants.",
    origin: "<p>Parents’ country of origin matters for policy because it influences the types of <a href='https://www.urban.org/research/publication/ten-years-language-access-washington-dc' target='_blank'>language access</a> and <a href='https://www.urban.org/research/publication/expanding-preschool-access-children-immigrants-executive-summary' target='_blank'>cultural competence</a> strategies necessary to serve children and their parents.</p><p>Nationally, as of 2022, 32 percent of children of immigrants had a primary parent from Mexico, 21 percent from the rest of Central America and South America, and 47 percent from other parts of the world. However, this varies considerably across states. In California, for example, 47 percent of children of immigrants in 2022 had immigrant parents from Mexico, compared with only 8 percent in New York.</p><p>(When parents are from different regions, the child is assigned the <a href='http://webapp.urban.org/charts/datatool/pages.cfm?p=technicalappendix' target='_blank'>primary parent’s</a> region of origin.)</p>",
    race: "<p>Discrimination and structural barriers tied to race and ethnicity can <a href='https://www.jstor.org/stable/20681749?seq=1#metadata_info_tab_contents'>compound</a> the challenges that children of immigrants and their families face, and immigrant and racial identity <a href='https://www.urban.org/research/publication/immigrant-youth-outcomes-patterns-generation-and-race-and-ethnicity'>can interact</a> in ways that influence these groups’ outcomes.</p><p>The majority of children of immigrants in the US are Hispanic (51 percent in 2022). Additionally, the share of children of immigrants who are Black and the share who are Asian or Pacific Islander has increased slightly over time. (Because of small sample sizes, Native Americans are counted in the “another race or multiracial” category for these maps.)</p>",
    citizenship: "<p>Citizenship is a <a href='https://www.urban.org/research/publication/economic-impact-naturalization-immigrants-and-cities'>key component</a> of immigrant integration and affects eligibility to vote, access to some jobs, and the ability to participate in many public programs. As of 2022, almost all (91 percent) children of immigrants were US citizens, a share that has grown over time. Also, most children of immigrants (65 percent in 2022) are US citizens with at least one US-citizen parent, and another 26 percent are US-citizen children with only noncitizen parents.</p><p>Noncitizen parents are <a href='https://www.urban.org/research/publication/low-income-immigrant-families-access-snap-and-tanf'>less likely to participate</a> in <a href='https://www.urban.org/research/publication/comprehensive-review-immigrant-access-health-and-human-services'>programs</a> like the Supplemental Nutrition Assistance Program or Temporary Assistance for Needy Families, even when their citizen children are eligible, which <a href='https://www.urban.org/research/publication/proposed-snap-work-requirements-and-childrens-food-security' target='_blank'>can have negative impacts on the children</a>. Note that noncitizen immigrants include people with green cards or temporary visas and <a href='https://www.urban.org/2016-analysis/we-people-includes-immigrants' target='_blank'>a minority</a> who are unauthorized or have temporary protections.</p>",
    edukids: "<p>Education is a <a href='https://www.urban.org/research/publication/earnings-dynamics-role-education-throughout-workers-career' target='_blank'>key factor</a> in children’s future success. School enrollment rates are similar for children of immigrants and children of only US-born parents. Nearly all children ages 6 to 17 are enrolled in school. The share of children ages 3 to 5 in either school or preschool is generally lower and similar for both of these groups. However, children of immigrants ages 3 to 5 are more likely to be enrolled in kindergarten or grade school and less likely to be enrolled in <a href='https://www.urban.org/research/publication/preparing-future-workforce-early-care-and-education-participation-among-children-immigrants' target='_blank'>preschool</a> than children ages 3 to 5 with only US-born parents.</p><p>Enrollment for children of immigrants ages 3 to 5 fell during the pandemic from around 60 percent before 2020 to 51 percent in 2021 and 55 percent in 2022. Young children with only US-born parents experienced smaller enrollment declines from about 60 percent prepandemic to 54 percent in 2021 and 57 percent in 2022.</p>",
    edupar: "<p>A child’s chances of success <a href='https://www.urban.org/research/publication/child-poverty-and-adult-success' target='_blank'>significantly increase</a> if the child has a parent with a college degree. A large share of children of immigrants (42 percent in 2022) have a parent who has completed college or an advanced degree, slightly lower than the share for children with only US-born parents (46 percent). However, a relatively high share of children of immigrants (17 percent) have parents with less than a high school education, which is much higher than the share for children with only US-born parents (4 percent). (If parents in two-parent families have different educational attainment levels, we use the higher of the two parents.)</p>",
    engkids: '<p>Knowing what share of children in the state or community are English proficient is important for shaping local <a href="https://www.urban.org/research/publication/ten-years-language-access-washington-dc" target="_blank">language-access strategies</a>. The vast majority of children of immigrants are English proficient (86 percent in 2022). A small share—14 percent in 2022—has limited English proficiency, which is <a href="http://webapp.urban.org/charts/datatool/pages.cfm?p=technicalappendix" target="_blank">defined as</a> speaking English less than “very well.”</p>',
    engpar: '<p>English proficiency affects parents’ ability to <a href="https://www.urban.org/research/publication/upskilling-immigrant-workforce-meet-employer-demand-skilled-workers" target="_blank">obtain a good job</a>, <a href="https://www.fcd-us.org/children-in-immigrant-families-ensuring-opportunity-for-every-child-in-america/" target="_blank">find and enroll in public programs</a>, <a href="https://www.urban.org/research/publication/limited-english-proficiency-barrier-homeownership" target="_blank">own a home</a>, and <a href="https://www.urban.org/research/publication/expanding-preschool-access-children-immigrants" target="_blank">navigate their children’s early education and school systems</a>. About 66 percent of children of immigrants have at least one English-proficient parent, with 48 percent having all English-proficient parents. Nevertheless, in 2022, 16 percent of children of immigrants lived in linguistically isolated households, meaning that no family members older than age 14 were proficient in English. Limited English proficiency is <a href="http://webapp.urban.org/charts/datatool/pages.cfm?p=technicalappendix" target="_blank">defined as</a> reporting speaking English less than “very well.”</p>',
    numkids: "<p>Almost four out of five children of immigrants live with siblings, which, on one hand, can mean challenges such as greater household costs and more complicated work and care schedules for parents and families. On the other hand, siblings can be beneficial in helping care for younger children and providing linguistic and other intellectual enrichment. In 2022, 23 percent of children of immigrants lived in families with only one child and 40 percent were in families with two children, compared with 24 and 39 percent, respectively, for children of only US-born parents. The share of children in families with three or more children was 38 percent for children of immigrants and 37 percent for children of US-born parents.</p>",
    numpar: "<p>Living in a two-parent family is associated with <a href='https://www.urban.org/research/publication/childrens-family-environment' target='_blank'>greater stability and richer childhood environments</a>, greater potential availability to <a href='https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3972341/' target='_blank'>provide child care</a>, and <a href='https://www.urban.org/research/publication/families-and-economic-mobility' target='_blank'>higher family incomes</a> given both parents are potential workers. Children of immigrants are more likely to live in two-parent homes than children of only US-born parents. In 2022, 83 percent of children of immigrants lived in two-parent homes compared with 71 percent of children of only US-born parents.</p>",
    incbenefits: "<p>Children of immigrants are slightly more likely than those with only US-born parents to live in families with incomes below the federal poverty level, even though they are about equally likely to be in families with <a href='http://webapp.urban.org/charts/datatool/pages.cfm?p=technicalappendix' target='_blank'>substantial work hours</a>—meaning all adults in the family worked either 1,000 hours or more, on average, or 1,800 hours or more combined in the prior year.</p><p>In 2022, 17 percent of children of immigrants lived in families with incomes below the federal poverty level compared with 14 percent of children of only US-born parents. At the same time, 90 percent of children of immigrants were in families working substantial hours versus 89 percent of children of only US-born parents.</p><p>Looking at benefits, the share of both children of immigrants and children overall not covered by health insurance had been falling since 2009 (the first year this information is available), before stagnating in 2017 and increasing in 2018 and 2019. Refined health insurance coverage data used in this tool were only available through 2019 as of publication.</p>",
    housetrans: "<p>High housing and utility costs can put financial strain on children’s households, and being burdened by these costs is an indicator of <a href='https://www.urban.org/research/publication/material-hardship-among-nonelderly-adults-and-their-families-2017' target='_blank'>material hardship</a>. Children of immigrants are more likely to live in households burdened by housing and utility costs than children of only US-born parents.</p><p>In 2022, 42 percent of children of immigrants belonged to households that spent 30 percent or more of their income on housing and utility costs compared with 33 percent of children of only US-born parents. This percentage has declined for both groups over time.</p><p>The majority of children of immigrants also live in households that own their home, and almost all are in households with one or more vehicles available.</p>",
    paryears: "<p>Most children of immigrants’ parent(s) have lived in the US for many years. Additionally, 30 percent of children of immigrants have a US-born parent, most of whom are partnered with an immigrant parent who has been in the US for many years. In 2022, three-quarters of children of immigrants had parents who had all been in the US for 10 years or more. This share has increased over time, reflecting the growing number of immigrants who have been in the US for a relatively long time. For children with two foreign-born parents, the data below reflect the parent who arrived in the US most recently.</p>",
    disabledfam: "<p>Compared with adults without disabilities, those with a disability are <a href='https://www.urban.org/research/publication/stronger-social-security-disability-insurance-program-opens-door-early-intervention' target='_blank'>much less likely to be employed</a>, <a href='https://www.urban.org/research/publication/work-ability-and-social-insurance-safety-net-years-prior-retirement' target='_blank'>more likely to be poor</a>, and often <a href='https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4802361/' target='_blank'>reliant on friends or family to care for them</a> either directly or financially. Children of immigrants are less likely to live in a family with an adult with a disability than are children of only US-born parents. This is primarily because children of immigrants are less likely to have a parent with a disability, as they are around equally as likely to have a nonparent adult in the family who has a disability. In 2022, 8 percent of children of immigrants had a parent with a disability compared with 12 percent of children of only US-born parents.</p>",
    vetpar: "<p>Only 7 percent of all children have a veteran parent, but those who do may have unique <a href='https://www.urban.org/research/publication/state-post-911-veteran-families' target='_blank'>strengths and challenges</a>. Veteran parents may be disabled as a result of their service, and partner military benefits are often <a href='http://archive.defense.gov/news/Same-SexBenefitsMemo.pdf' target='_blank'>contingent on marital status</a>. Children of immigrants are less likely to have a veteran parent than children of only US-born parents (3 and 8 percent, respectively, in 2022). This difference is partly because many immigrant parents have lived in the US, and had an opportunity to serve, for less of their lives and are <a href='https://fas.org/sgp/crs/homesec/IF10884.pdf' target='_blank'>usually required</a> to be US citizens or lawful permanent residents to serve. However, the share of children of immigrants with a veteran parent varies geographically, with much higher rates in some states with large military and veteran populations, such as West Virginia and Alaska.</p>"
};